### PR TITLE
feat: adding documentation for filter admin endpoint

### PR DESCRIPTION
**Pull request by gabrielmer**
Documenting new `/admin/v1/filter/subscriptions` endpoint introduced in in https://github.com/waku-org/nwaku/pull/2314

image

### CODE REVIEW

**Review by SionoiS — APPROVED** [review]
LGTM thank you!

**Review by NagyZoltanPeter — APPROVED** [review]
Great one! Thank you.

**Comment by gabrielmer** [comment]
@chaitanyaprem now that documentation is updated, we should probably open a ticket to include the endpoint in go-waku too. WDYT?

**Comment by chaitanyaprem** [comment]
> @chaitanyaprem now that documentation is updated, we should probably open a ticket to include the endpoint in go-waku too. WDYT?

Done, reference https://github.com/waku-org/go-waku/issues/1002

**Pull request merged**
