### PR TITLE
chore: adding origin to WakuPeer schema

### PR DESCRIPTION
**Pull request by gabrielmer**
Updating API specification following https://github.com/waku-org/nwaku/pull/2848

### CODE REVIEW

**Review by NagyZoltanPeter — APPROVED** [review]
Yes, it is matching to code!!! Thank you.

**Review by Ivansete-status — APPROVED** [review]
LGTM! Thanks for it! :100: 
We need to make sure the example is properly updated in the following as well:
https://waku-org.github.io/waku-rest-api/

( cc @NagyZoltanPeter )

**Comment by NagyZoltanPeter** [comment]
> LGTM! Thanks for it! 💯 We need to make sure the example is properly updated in the following as well: https://waku-org.github.io/waku-rest-api/
> 
> ( cc @NagyZoltanPeter )

I think that one is automagically done, as the page is fed from this repo from latest master. :-)

**Comment by gabrielmer** [comment]
It did get updated :)

image

I'll create another PR marking origin as required so it has the red asterisk as the other fields for consistency.
It makes no difference in practice as there's no endpoint or anything where the user sets all those values, but better to be consistent

**Pull request merged**
